name: CI

on:
  workflow_dispatch:
    inputs:
      new_release:
        type: boolean
        description: Force new Release
      dont_update:
        type: boolean
        description: Don't update

  # schedule:
  #   - cron: "0 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ch5-crcomlib-core
      VERSIONS_REPOSITORY: ${{ github.repository_owner }}/versions
      CH5_LATEST: ${{ github.event.inputs.dont_update == 'true' && 'no' || 'yes' }}
      SHOULD_BUILD: ${{ github.event.inputs.new_release == 'true' && 'yes' || 'no' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Show Environment
        run: env | sort

      - name: Get Remote
        run: . get_repo.sh

      - name: Check Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_RELEASE: ${{ github.event.inputs.new_release }}
          IS_SPEARHEAD: "yes"
        run: . check_version.sh

      - name: Build
        if: env.SHOULD_BUILD == 'yes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.sh

      - name: Update Version
        if: env.SHOULD_BUILD == 'yes' && github.event.inputs.dont_update != 'true'
        run: ./update_version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
